services:
  # Backe  # Frontend static site
  - type: web
    name: aws-iam-assessment-ui
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://aws-iam-assessment-api.onrender.com # Will be updated with actual backend URLrvice
  - type: web
    name: aws-iam-assessment-api
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
    autoDeploy: true

  # Frontend static site
  - type: web
    name: aws-iam-assessment-ui
    buildCommand: cd frontend && npm install && npm run build
    staticDistDirectory: dist
    rootDirectory: frontend
    envVars:
      - key: VITE_API_URL
        value: https://aws-iam-assessment-api.onrender.com # Will be updated with actual backend URL
